from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required

from src.extensions import db
from src.models import DividendReceived
from src.services.dividends import DividendsService
from src.services.portfolio import PortfolioService

dividends_bp = Blueprint('dividends', __name__)


@dividends_bp.route('/dividends', methods=['GET'])
@login_required
def dividends_page():
    # Suggestions are normally generated by the nightly snapshot job; doing it
    # here too means an order added today shows its dividends immediately.
    PortfolioService(current_user.id).sync_suggested_dividends()
    db.session.commit()

    service = DividendsService(current_user.id)
    context = {
        'kpis': service.kpis(),
        'monthly': service.monthly_received(),
        'positions': service.by_position(),
        'calendar': service.upcoming_calendar(),
        'suggestions': service.pending_suggestions(),
    }
    return render_template('dividends.html', warnings=sorted(set(service.warnings)), **context)


def _resolve_suggestion(dividend_id):
    return DividendReceived.query.filter_by(id=dividend_id, user_id=current_user.id).first()


@dividends_bp.route('/dividends/<int:dividend_id>/confirm', methods=['POST'])
@login_required
def confirm_dividend(dividend_id):
    row = _resolve_suggestion(dividend_id)
    if row is None:
        return {'message': 'Dividend not found'}, 404
    row.confirmed = True
    db.session.commit()

    if request.headers.get('HX-Request'):
        return '', 204
    flash('Dividendo confirmado', 'success')
    return redirect(url_for('dividends.dividends_page'))


@dividends_bp.route('/dividends/<int:dividend_id>/dismiss', methods=['POST'])
@login_required
def dismiss_dividend(dividend_id):
    row = _resolve_suggestion(dividend_id)
    if row is None:
        return {'message': 'Dividend not found'}, 404
    row.dismissed = True
    db.session.commit()

    if request.headers.get('HX-Request'):
        return '', 204
    flash('Sugerencia descartada', 'success')
    return redirect(url_for('dividends.dividends_page'))
