"""empty message

Revision ID: 349953e6ad93
Revises: 5bf8a61b1df1
Create Date: 2024-12-30 10:33:16.491352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '349953e6ad93'
down_revision = '5bf8a61b1df1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('symbol', sa.String(length=10), nullable=False))
        batch_op.create_foreign_key('fk_stocks_tickets', 'tickets', ['symbol'], ['symbol'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.drop_constraint('fk_stocks_tickets', type_='foreignkey')
        batch_op.drop_column('symbol')

    # ### end Alembic commands ###
