"""empty message

Revision ID: 4aaf4c55eabb
Revises: 4f5f7fed3fe1
Create Date: 2025-01-11 12:51:08.704125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4aaf4c55eabb'
down_revision = '4f5f7fed3fe1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.alter_column('current_cost',
               existing_type=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.alter_column('current_cost',
               existing_type=sa.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###
