"""creating tables for stocks, orders and portfolio

Revision ID: 4e9f4f5465d6
Revises: 
Create Date: 2025-01-02 16:12:09.147362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e9f4f5465d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('root_symbol', sa.String(length=6), nullable=True),
    sa.Column('long_name', sa.String(length=100), nullable=True),
    sa.Column('short_name', sa.String(length=10), nullable=True),
    sa.Column('website', sa.String(length=100), nullable=True),
    sa.Column('cvm_code', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('BUY', 'SELL', name='ordertype'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.symbol'], name='fk_orders_stocks'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_portfolio_users', sa.Integer(), nullable=False),
    sa.Column('fk_portfolio_stocks', sa.Integer(), nullable=False),
    sa.Column('avg_price', sa.Float(), nullable=True),
    sa.Column('actual_price', sa.Float(), nullable=True),
    sa.Column('adquisition_cost', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('profit', sa.Float(), nullable=False),
    sa.Column('percent_return', sa.Float(), nullable=False),
    sa.Column('dividend_amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['fk_portfolio_stocks'], ['stocks.id'], ),
    sa.ForeignKeyConstraint(['fk_portfolio_users'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('portfolios')
    op.drop_table('orders')
    op.drop_table('stocks')
    # ### end Alembic commands ###
