"""empty message

Revision ID: 608df8f5eda7
Revises: 4aaf4c55eabb
Create Date: 2025-01-11 12:51:59.246619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '608df8f5eda7'
down_revision = '4aaf4c55eabb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.alter_column('profit',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('percent_return',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('dividend_amount',
               existing_type=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.alter_column('dividend_amount',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('percent_return',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('profit',
               existing_type=sa.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###
