"""empty message

Revision ID: 7b9607edd2fa
Revises: 6391f5c6514d
Create Date: 2024-12-23 17:28:57.579290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b9607edd2fa'
down_revision = '6391f5c6514d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=7), nullable=False))

    # ### end Alembic commands ###
