"""add floatshares

Revision ID: 807a972463c7
Revises: 4e9f4f5465d6
Create Date: 2025-01-02 16:18:13.694677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '807a972463c7'
down_revision = '4e9f4f5465d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('floatShares', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.drop_column('floatShares')

    # ### end Alembic commands ###
