"""add community and market indicators

Revision ID: b1e1a810de86
Revises: 6c1f7a92d4e8
Create Date: 2026-08-20 13:43:34.062152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1e1a810de86'
down_revision = '6c1f7a92d4e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_indicators',
    sa.Column('key', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=32), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('change_percent', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('community_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('ANALYSIS', 'QUESTION', 'DIVIDENDS', 'NEWS', 'TRADES', 'SUGGESTIONS', name='postcategory'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('community_posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_community_posts_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_posts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_posts_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_posts_user_id'), ['user_id'], unique=False)

    op.create_table('community_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['community_posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('community_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_community_comments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_comments_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_comments_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_comments_user_id'), ['user_id'], unique=False)

    op.create_table('community_post_mentions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['community_posts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'asset_id', name='uq_community_mention_post_asset')
    )
    with op.batch_alter_table('community_post_mentions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_community_post_mentions_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_post_mentions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_post_mentions_post_id'), ['post_id'], unique=False)

    op.create_table('community_post_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['community_posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'user_id', name='uq_community_report_post_user')
    )
    with op.batch_alter_table('community_post_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_community_post_reports_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_post_reports_user_id'), ['user_id'], unique=False)

    op.create_table('community_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['community_posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'post_id', name='uq_community_vote_user_post')
    )
    with op.batch_alter_table('community_votes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_community_votes_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_votes_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        # server_default is required: existing rows have no value for a NOT
        # NULL column, and the Python-side default only applies to inserts
        # SQLAlchemy performs, not to the ALTER TABLE itself.
        batch_op.add_column(
            sa.Column('is_admin', sa.Boolean(), nullable=False, server_default=sa.false())
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    with op.batch_alter_table('community_votes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_community_votes_user_id'))
        batch_op.drop_index(batch_op.f('ix_community_votes_post_id'))

    op.drop_table('community_votes')
    with op.batch_alter_table('community_post_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_community_post_reports_user_id'))
        batch_op.drop_index(batch_op.f('ix_community_post_reports_post_id'))

    op.drop_table('community_post_reports')
    with op.batch_alter_table('community_post_mentions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_community_post_mentions_post_id'))
        batch_op.drop_index(batch_op.f('ix_community_post_mentions_created_at'))
        batch_op.drop_index(batch_op.f('ix_community_post_mentions_asset_id'))

    op.drop_table('community_post_mentions')
    with op.batch_alter_table('community_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_community_comments_user_id'))
        batch_op.drop_index(batch_op.f('ix_community_comments_post_id'))
        batch_op.drop_index(batch_op.f('ix_community_comments_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_community_comments_created_at'))

    op.drop_table('community_comments')
    with op.batch_alter_table('community_posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_community_posts_user_id'))
        batch_op.drop_index(batch_op.f('ix_community_posts_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_community_posts_created_at'))
        batch_op.drop_index(batch_op.f('ix_community_posts_category'))

    op.drop_table('community_posts')
    op.drop_table('market_indicators')
    # ### end Alembic commands ###
