"""company_events + company_event_reads, assets.cik, dividend_received.dismissed

Revision ID: c7a5e1d93f20
Revises: fd25f982cca1
Create Date: 2026-08-20 15:30:00.000000

Hand-written, not autogenerated: `flask db migrate` reflects every table in
the dev DB, including unrelated legacy tables from another project, and fails
on a dangling FK there (see a1f42e9c8b3d for the full note).
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7a5e1d93f20'
down_revision = 'fd25f982cca1'
branch_labels = None
depends_on = None


def upgrade():
    op.create_table(
        'company_events',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('asset_id', sa.Integer(), nullable=False),
        sa.Column(
            'kind',
            sa.Enum('FILING', 'EARNINGS', 'DIVIDEND', 'NEWS', name='companyeventkind'),
            nullable=False,
        ),
        sa.Column('source', sa.String(length=16), nullable=False),
        sa.Column('external_id', sa.String(length=64), nullable=True),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('summary', sa.Text(), nullable=True),
        sa.Column('url', sa.String(length=512), nullable=True),
        sa.Column('published_at', sa.DateTime(), nullable=False),
        sa.Column('event_date', sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('asset_id', 'source', 'external_id', name='uq_company_event_asset_source_external'),
    )
    with op.batch_alter_table('company_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_events_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_events_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_events_published_at'), ['published_at'], unique=False)

    op.create_table(
        'company_event_reads',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('company_event_id', sa.Integer(), nullable=False),
        sa.Column('read_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['company_event_id'], ['company_events.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'company_event_id', name='uq_company_event_read_user_event'),
    )
    with op.batch_alter_table('company_event_reads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_event_reads_user_id'), ['user_id'], unique=False)
        batch_op.create_index(
            batch_op.f('ix_company_event_reads_company_event_id'), ['company_event_id'], unique=False
        )

    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cik', sa.String(length=10), nullable=True))

    with op.batch_alter_table('dividend_received', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('dismissed', sa.Boolean(), nullable=False, server_default=sa.false())
        )


def downgrade():
    with op.batch_alter_table('dividend_received', schema=None) as batch_op:
        batch_op.drop_column('dismissed')

    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_column('cik')

    with op.batch_alter_table('company_event_reads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_event_reads_company_event_id'))
        batch_op.drop_index(batch_op.f('ix_company_event_reads_user_id'))
    op.drop_table('company_event_reads')

    with op.batch_alter_table('company_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_events_published_at'))
        batch_op.drop_index(batch_op.f('ix_company_events_kind'))
        batch_op.drop_index(batch_op.f('ix_company_events_asset_id'))
    op.drop_table('company_events')
